language: python
sudo: false
python:
  - "3.5"
addons:
  postgresql: 9.4
env:
  - REQ="Django>=1.11,<2.0"
  - REQ="Django==2.0b1"
install:
  - pip install $REQ psycopg2 pytz
  - python setup.py install
script: "cd tests && ./manage.py test -v 2 testapp"
